### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by mbcrocci** [g4rrucho/Trabalho_Prog#3]
Posso estar a perceber mal porque não sei bem o enunciado.

Ao jogar ele escreve numa posição que não faz parte do tabuleiro.

Exemplo: Columns = 6, Lines = 4
Jogada 1 -> 5 4
Jogada 2 -> 3 5
Jogada 3 -> Tentei 1 1, 1 2, 1 3, 1 4, 2 1, 2 2, 2 3, 2 4
                    Funcionou 6 4
Jogada 4 -> 15 5 (claramente fora do tabuleiro)

**Comment by g4rrucho** [comment]
Tenho de repensar a validação. Por que condição a função vai começar a "validar".

**Comment by g4rrucho** [comment]
Validation is working. Algorithm is correct.
