### ISSUE TITLE
Pointer arithmetic

### ISSUE THREAD

**Issue by mbcrocci** [g4rrucho/Trabalho_Prog#4]
Tenho de confirmar a tua aritmetica de ponteiros, nao sei se esta certa xD
Os loops parecem-me errados e acho que seria mais facil fazer:
`for(i = 0; i < linhas; i++)
     for(j = 0; j <colunas;  j++)
         board[i][j];`

**Comment by g4rrucho** [comment]
Mesmo problema da validação. O algoritmo não estava corretamente escrito. Resolvido.
